version: "2"
services:
    dev:
        image: portfolio-front
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./public
              target: /app/public
              read_only: true
            - type: bind
              source: ./src
              target: /app/src
              read_only: true
